"""Compatibility CLI for the shared US equities market-session calendar."""

from intraday_scanner.market_calendar import (
    CALENDAR_AUTHORITY,
    CALENDAR_COVERAGE_END,
    CALENDAR_COVERAGE_START,
    CALENDAR_ID,
    CALENDAR_PUBLISHED_AS_OF,
    CALENDAR_SOURCE_REFS,
    EARLY_CLOSE_ET,
    FIRST_ELIGIBLE_ACTIVATION_POLICY,
    MARKET_TIMEZONE,
    NEXT_SESSION_ACTIVATION_POLICY,
    REGULAR_CLOSE_ET,
    REGULAR_OPEN_ET,
    US_MARKET_EARLY_CLOSES,
    US_MARKET_EARLY_CLOSES_2026,
    US_MARKET_EARLY_CLOSES_2027,
    US_MARKET_EARLY_CLOSES_2028,
    US_MARKET_HOLIDAYS,
    US_MARKET_HOLIDAYS_2026,
    US_MARKET_HOLIDAYS_2027,
    US_MARKET_HOLIDAYS_2028,
    MarketSessionDecision,
    MarketSessionStatus,
    core_session_phase,
    early_close_time_ct,
    first_eligible_session_date,
    is_market_day,
    is_market_holiday,
    is_weekday_market_day,
    main,
    market_session,
    next_market_day,
    next_session_after_registration,
    registration_coverage_inception_date,
    session_for_timestamp,
)

__all__ = [
    "CALENDAR_AUTHORITY",
    "CALENDAR_COVERAGE_END",
    "CALENDAR_COVERAGE_START",
    "CALENDAR_ID",
    "CALENDAR_PUBLISHED_AS_OF",
    "CALENDAR_SOURCE_REFS",
    "EARLY_CLOSE_ET",
    "FIRST_ELIGIBLE_ACTIVATION_POLICY",
    "MARKET_TIMEZONE",
    "NEXT_SESSION_ACTIVATION_POLICY",
    "REGULAR_CLOSE_ET",
    "REGULAR_OPEN_ET",
    "US_MARKET_EARLY_CLOSES",
    "US_MARKET_EARLY_CLOSES_2026",
    "US_MARKET_EARLY_CLOSES_2027",
    "US_MARKET_EARLY_CLOSES_2028",
    "US_MARKET_HOLIDAYS",
    "US_MARKET_HOLIDAYS_2026",
    "US_MARKET_HOLIDAYS_2027",
    "US_MARKET_HOLIDAYS_2028",
    "MarketSessionDecision",
    "MarketSessionStatus",
    "core_session_phase",
    "early_close_time_ct",
    "first_eligible_session_date",
    "is_market_holiday",
    "is_market_day",
    "is_weekday_market_day",
    "main",
    "market_session",
    "next_market_day",
    "next_session_after_registration",
    "registration_coverage_inception_date",
    "session_for_timestamp",
]


if __name__ == "__main__":
    raise SystemExit(main())
