"""Typed v2 domain contracts."""

from intraday_scanner.v2.contracts.common import (
    DataSourceId,
    ScalarValue,
    StrategyId,
    StrategyVersion,
    Symbol,
)
from intraday_scanner.v2.contracts.data import (
    AssetClass,
    Bar,
    BarBatch,
    DataSnapshot,
    DataValidationIssue,
    DataValidationReport,
    DataValidationSeverity,
    DataValidationStatus,
    Timeframe,
)
from intraday_scanner.v2.contracts.outcomes import (
    BacktestSummary,
    HistoricalReturnSummary,
    OutcomeLabel,
    PerformanceMetric,
    ReportArtifact,
    TradeOutcome,
)
from intraday_scanner.v2.contracts.risk import (
    DecisionCard,
    PositionSizingInput,
    PositionSizingResult,
    RiskConfig,
    TradePlan,
)
from intraday_scanner.v2.contracts.scan import (
    ScanCandidate,
    ScanResult,
    ScoreComponent,
    SetupScore,
    SignalDirection,
    SignalEvidence,
    SignalStatus,
)
from intraday_scanner.v2.contracts.serialization import (
    ContractMixin,
    ContractValidationError,
    contract_from_dict,
    contract_from_json,
    contract_to_dict,
    contract_to_json,
)

__all__ = [
    "AssetClass",
    "BacktestSummary",
    "Bar",
    "BarBatch",
    "ContractMixin",
    "ContractValidationError",
    "DataSnapshot",
    "DataSourceId",
    "DataValidationIssue",
    "DataValidationReport",
    "DataValidationSeverity",
    "DataValidationStatus",
    "DecisionCard",
    "HistoricalReturnSummary",
    "OutcomeLabel",
    "PerformanceMetric",
    "PositionSizingInput",
    "PositionSizingResult",
    "ReportArtifact",
    "RiskConfig",
    "ScalarValue",
    "ScanCandidate",
    "ScanResult",
    "ScoreComponent",
    "SetupScore",
    "SignalDirection",
    "SignalEvidence",
    "SignalStatus",
    "StrategyId",
    "StrategyVersion",
    "Symbol",
    "Timeframe",
    "TradeOutcome",
    "TradePlan",
    "contract_from_dict",
    "contract_from_json",
    "contract_to_dict",
    "contract_to_json",
]
